---
-
    name: Ensure that php is installed and configured
    hosts: acme
    become: true
    roles:
        - geerlingguy.php-versions
        - geerlingguy.php-xdebug
        - geerlingguy.php-mysql
    vars:
        php_packages:
            - php{{ php_default_version_debian }}-common
            - php{{ php_default_version_debian }}-cli
            - php{{ php_default_version_debian }}-dev
            - php{{ php_default_version_debian }}-fpm
            - php{{ php_default_version_debian }}-soap
            - php{{ php_default_version_debian }}-intl
            - libpcre3-dev
            - php{{ php_default_version_debian }}-curl
            - php{{ php_default_version_debian }}-json
            - php{{ php_default_version_debian }}-xml
            - php{{ php_default_version_debian }}-mbstring
        php_packages_extra:
            - php-bcmath
            - php-zip
        php_enable_webserver: false
        php_enable_php_fpm: true
        php_fpm_pool_user: vagrant
        php_fpm_pool_group: vagrant
        php_enable_apc: false
        php_opcache_enable: false
        php_error_reporting: "-1"
        php_date_timezone: "Europe/Berlin"
        php_display_errors: "On"
        php_display_startup_errors: "On"
        php_session_save_path: "/var/lib/php/sessions"
        ## Xdebug
        php_xdebug_version: 2.6.1
        php_xdebug_default_enable: 1
        php_xdebug_remote_enable: "true"
        php_xdebug_remote_connect_back: "true"
        php_xdebug_idekey: "PHPSTORM"

-
    hosts: acme
    roles:
        - geerlingguy.composer
    vars:
        composer_keep_updated: true