---
-
    name: geerlingguy.php-xdebug
    version: 3.0.0
-
    name: geerlingguy.php-versions
    version: 4.0.3
-
    name: geerlingguy.php-mysql
    version: 2.0.2
-
    name: geerlingguy.mysql
    version: 3.1.0
-
    name: geerlingguy.nginx
    version: 2.7.0
-
    name: jdauphant.ssl-certs
    version: v1.7.1
-
    name: geerlingguy.composer
    version: 1.7.6